// ------------------------------------------------------------------------------
// <auto-generated>
//     This file was generated by VSIX Synchronizer
// </auto-generated>
// ------------------------------------------------------------------------------
namespace CopyFileToDir
{
    using System;
    
    /// <summary>
    /// Helper class that exposes all GUIDs used across VS Package.
    /// </summary>
    internal sealed partial class PackageGuids
    {
        public const string guidCopyFileToDirPackageString = "859e9969-dce4-4a75-8c8b-4da8aae6b893";
        public static Guid guidCopyFileToDirPackage = new Guid(guidCopyFileToDirPackageString);

        public const string guidCopyFileToDirPackageCmdSetString = "02caf327-9c63-40c4-ab52-57516ca371e8";
        public static Guid guidCopyFileToDirPackageCmdSet = new Guid(guidCopyFileToDirPackageCmdSetString);

        public const string guidImagesString = "2f4b2dea-f204-4ba7-8780-236f2664a450";
        public static Guid guidImages = new Guid(guidImagesString);
    }
    /// <summary>
    /// Helper class that encapsulates all CommandIDs uses across VS Package.
    /// </summary>
    internal sealed partial class PackageIds
    {
        public const int MyMenuGroup = 0x1020;
        public const int CopyFileToDirCommandId = 0x0100;
        public const int bmpPic1 = 0x0001;
        public const int bmpPic2 = 0x0002;
        public const int bmpPicSearch = 0x0003;
        public const int bmpPicX = 0x0004;
        public const int bmpPicArrows = 0x0005;
        public const int bmpPicStrikethrough = 0x0006;
    }
}